### ISSUE TITLE
Scheduled backup failed if pxc cluster name is not unique across namespaces

### ISSUE THREAD

**Issue by ebuildy** [percona/percona-xtradb-cluster-operator#1544]
We run 2 pxc instances with same name "pxc-mysql" in 2 different namespaces: "a" , "b".
We try to schedule a backup for "a" but this is not working, it seem the backup job is removed all the time:

```
{"level":"info""msg":"Creating or updating backup job","controller":"pxc-controller","namespace":"a","name":"pxc-mysql","reconcileID":"fa7b0439-....83ee7e","name":"80527-jayjay","schedule":"*/2 * * * *"}
{"level":"info",,"msg":"deleting outdated backup job","controller":"pxc-controller","namespace":"b","name":"pxc-mysql","reconcileID":"1e5fa590....9df3","name":"80527-jayjay"}
```

dont know "deleting outdated backup job" in namespace "b"

Changing the name of instance in ns "a" did the trick.

**Is pxc cluster name must be unique across namespaces?**

**Comment by hors** [comment]
Hi @ebuildy, it seems I can reproduce it as well :( We will try to include a fix in the next PXCO release. Thank you for the report.

**Comment by egegunes** [comment]
Created [K8SPXC-1333](https://jira.percona.com/browse/K8SPXC-1333) for internal tracking.

**Comment by hors** [comment]
Hi @ebuildy, the issue was fixed and will be included in next PXCO release. I hope we will have a release in the first part of the next month.

**Comment by ebuildy** [comment]
ho yeah!!

Many thanks
