### ISSUE TITLE
PXC restore jobs pod resources requests values are overwritten by spec.resources.limits attributes from pxc-restore resource definition

### ISSUE THREAD

**Issue by konoox** [percona/percona-xtradb-cluster-operator#1671]
### Report

PXC restore jobs pod resources requests values are overwritten by spec.resources.limits attributes from pxc-restore resource definition.

### More about the problem

When you create a new pxc-restore resource, you can specify spec.resources.requests and spec.resources.limits attributes in the yaml definition. However, no matter what you put inside the spec.resources.requests attributes, both resources requests and limits in the related jobs pod will take the values specified in spec.resources.limits attributes.

### Steps to reproduce

1 - Create a pxc cluster with a backup storage configured
2 - Run a pxc backup of the cluster and wait for its successfull completion
3 - Prepare a pxc restore definition targeting the previous backup with both spec.resources.requests and spec.resources.limits attributes defined with different values
4 - Apply the pxc restore resource on the cluster
5 - See that the related job pod resources requests and limits are only filled by the values specified in the spec.resources.limits attributes of the restore definition. spec.resources.requests attributes are just ignored.

### Versions

1 - Kubernetes - v1.27.6
2 - Operator - Percona Operator for MySQL based on Percona XtraDB Cluster 1.13.0
3 - Database - MySQL XtraDB 8.0

**Comment by spron-in** [comment]
Raised https://perconadev.atlassian.net/browse/K8SPXC-1379

**Comment by konoox** [comment]
OK : FIXED and VALIDATED in 1.15.0
